services:
  wordpress:
    image: wordpress:4.7.0
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wpdeface
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://wordpress');
        define('WP_HOME', 'http://wordpress');
    depends_on:
      - db
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      default:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdeface
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      default:

  deface-checker:
    build:
      context: .
      target: final
    environment:
      DEFACEMENT_CHECKED_SITE: ${DEFACEMENT_CHECKED_SITE}
      THROTTLE_TIME: ${THROTTLE_TIME}
      CHECKING_INTERVAL: ${CHECKING_INTERVAL}
    depends_on:
      - wordpress
    ports:
      - "5000:5000"
    networks:
      default:

volumes:
  db_data: