version: '3.1'

services:
  wordpress:
    image: wordpress:4.7.0
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wpdeface
    depends_on:
      - db
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      default:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdeface
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      default:

  detector:
    build: .
    depends_on:
      - wordpress
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      default:

volumes:
  db_data: